---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - wget
    - pwgen
    - htop-osx
    - ant
    - chromedriver
    - dart
    - dartium
    - docker
    - freetype
    - maven
    - nginx
    - ngrok
    - pyenv
    - pyenv-virtualenv
    - rbenv

- name: install dart and dartium
  homebrew: name=dart-lang/dart/dart state=latest install_options=with-dartium,with-content-shell

- name: install maven
  homebrew_cask: java
  homebrew: maven

- name: install developer cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - java
    - iterm2
