---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  homebrew_tap: tap=dart-lang/homebrew-dart state=present
  with_items:
    - wget
    - pwgen
    - htop-osx
    - ant
    - chromedriver
    - dart
    - dartium
    - docker
    - freetype
    - java
    - maven
    - nginx
    - ngrok
    - pyenv
    - pyenv-virtualenv
    - rbenv

- name: install developer cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - java
    - iterm2
